apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agnos-api
  namespace: argocd
spec:
  project: agnos
  source:
    repoURL: https://github.com/sudo-yama/agnos-gitops-infra.git
    targetRevision: main
    path: helm/api
    helm:
      releaseName: agnos-api
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true