apiVersion: v1
kind: Service
metadata:
  name: {{ include "agnos-api.fullname" . }}
  labels:
    {{- include "agnos-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "agnos-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP